# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
# Declaring Netlify serverless functions to handle Stripe API 
[build]

# Directory to change to before starting a build.
# This is where we will look for package.json/.nvmrc/etc.
# If not set, defaults to the root directory.
base = "./webstore"

[functions]
  # Directory with serverless functions, including background functions,
  # to deploy. This is relative to the base directory if one has been set, 
  # or the root directory if a base hasn't been set.
directory = "functions/"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200